// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYH_rI5Icv9G-g5uNU2-BiMpELlaN3XGk',
    appId: '1:644716286828:web:1e8d57212866e453ac1949',
    messagingSenderId: '644716286828',
    projectId: 'clica-c4bfc',
    authDomain: 'clica-c4bfc.firebaseapp.com',
    storageBucket: 'clica-c4bfc.firebasestorage.app',
    measurementId: 'G-08RNKRCNW2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiT4uuhAO0dQlEqCrf9cK6N1ovci1uurg',
    appId: '1:644716286828:android:0e497041ef656d4bac1949',
    messagingSenderId: '644716286828',
    projectId: 'clica-c4bfc',
    storageBucket: 'clica-c4bfc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4nSPAR8YVb_NsXtA4kmlMVwZ2XJBLvLo',
    appId: '1:644716286828:ios:b68dbe4380792b38ac1949',
    messagingSenderId: '644716286828',
    projectId: 'clica-c4bfc',
    storageBucket: 'clica-c4bfc.firebasestorage.app',
    iosBundleId: 'com.kannan7.clica',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYH_rI5Icv9G-g5uNU2-BiMpELlaN3XGk',
    appId: '1:644716286828:web:632d9f155df01ef1ac1949',
    messagingSenderId: '644716286828',
    projectId: 'clica-c4bfc',
    authDomain: 'clica-c4bfc.firebaseapp.com',
    storageBucket: 'clica-c4bfc.firebasestorage.app',
    measurementId: 'G-KTYVV8SD12',
  );
}
